'------------------------------------------------------------------------------
' <auto-generated>
'     Ten kod został wygenerowany przez narzędzie.
'     Wersja wykonawcza:4.0.30319.42000
'
'     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
'     kod zostanie ponownie wygenerowany.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    'przez narzędzie, takie jak ResGen lub Visual Studio.
    'Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    'z opcją /str lub ponownie utwórz projekt VS.
    '''<summary>
    '''  Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GuitarCenter_UI.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        '''  przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blac_customers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blac customers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property guitars() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("guitars", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property minimalize_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimalize_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property minimalize_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimalize_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property minmalize_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minmalize_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property No_Gwhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("No_Gwhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ok_Gwhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ok_Gwhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property topMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
