USE [master]
GO

/****** Object:  Database [GuitarCenter]    Script Date: 2022-04-15 15:08:10 ******/
CREATE DATABASE [GuitarCenter]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GuitarCenter', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL14.DARTNET\MSSQL\DATA\GuitarCenter.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GuitarCenter_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL14.DARTNET\MSSQL\DATA\GuitarCenter_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [GuitarCenter] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GuitarCenter].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GuitarCenter] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GuitarCenter] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GuitarCenter] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GuitarCenter] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GuitarCenter] SET ARITHABORT OFF 
GO

ALTER DATABASE [GuitarCenter] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GuitarCenter] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GuitarCenter] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GuitarCenter] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GuitarCenter] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GuitarCenter] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GuitarCenter] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GuitarCenter] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GuitarCenter] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GuitarCenter] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GuitarCenter] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GuitarCenter] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GuitarCenter] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GuitarCenter] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GuitarCenter] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GuitarCenter] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GuitarCenter] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GuitarCenter] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GuitarCenter] SET  MULTI_USER 
GO

ALTER DATABASE [GuitarCenter] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GuitarCenter] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GuitarCenter] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GuitarCenter] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GuitarCenter] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GuitarCenter] SET QUERY_STORE = OFF
GO

USE [GuitarCenter]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [GuitarCenter] SET  READ_WRITE 
GO


